name: local
variables:
  - name: baseUrl
    value: https://cheepcart-project.onrender.com
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGM4NzQyOGNkZjc3ZjQwOGJhZGJiMyIsImlhdCI6MTc3NzkwMjAzOCwiZXhwIjoxNzc4NTA2ODM4fQ.RjoFAS_G0u_gIZrO-zBhF3uttETr_oCtkm5btZHGjno
